# Generated by Django 4.2.3 on 2023-07-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_studies'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='complete_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
