# Generated by Django 4.2.3 on 2023-07-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('expedition', models.CharField(blank=True, max_length=100)),
                ('certfication_id', models.CharField(blank=True, max_length=100)),
                ('certificate_link', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='certifications/static/img/')),
            ],
        ),
    ]
